language: node_js
sudo: false
node_js:
- '5.0.0'
before_script:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
script:
  - node_modules/angular-cli/bin/ng build
  - node_modules/karma/bin/karma start --single-run